### ISSUE TITLE
茄皇已经修复了，想问下作者

### ISSUE THREAD

**Issue by lksky8** [LinYuanovo/scripts#12]
UA为什么不能固定一个

**Comment by LinYuanovo** [comment]
可以固定啊，有人说怕黑才弄了多个ua而已

**Comment by kkkkxl** [comment]
> > 可以固定啊，有人说怕黑才弄了多个ua而已
> 
> 明白

大佬带带阿,比心♥

**Comment by lksky8** [comment]
@kkkkxl 在我github

**Comment by kkkkxl** [comment]
> @kkkkxl 在我github

🆗

**Comment by RouJiANG-14** [comment]
> 可以固定啊，有人说怕黑才弄了多个ua而已

佬，茄皇报错提示sign error3是因为啥啊？？？
