### ISSUE TITLE
茄皇的url好像变了  助力也是

### ISSUE THREAD

**Issue by kkkkxl** [LinYuanovo/scripts#13]
![image](https://user-images.githubusercontent.com/37541028/198002573-97ba99a1-9b6c-41db-aeb3-f15d1cfb8348.png)

**Comment by kkkkxl** [comment]
【开始获取AU】
获取AU失败，原因是：There is no api match uri '/qiehuang/ga/public/api/login' host 'api.xiaoyisz.com'
【开始查询任务】
【开始收取阳光】
收取失败，原因是：There is no api match uri '/qiehuang/ga/user/daily/pickup' host 'api.xiaoyisz.com'

**Comment by guoioug** [comment]
变成apig.xiaoyisz.com了

**Comment by Deleted-Account** [comment]
+1
我也是这个报错

**Comment by Deleted-Account** [comment]
楼主解决了吗，我把脚本里的api.xiaoyisz全部改成抓包时候看见的apig.xiaoyis，没能正常跑起来

**Comment by kkkkxl** [comment]
> 楼主解决了吗，我把脚本里的api.xiaoyisz全部改成抓包时候看见的apig.xiaoyisz，没能正常跑起来

换其他的吧

**Comment by Deleted-Account** [comment]
> > 楼主解决了吗，我把脚本里的api.xiaoyisz全部改成抓包时候看见的apig.xiaoyisz，没能正常跑起来
> 
> 换其他的吧

可以给点提示吗？ 感恩

**Comment by kkkkxl** [comment]
> > > 楼主解决了吗，我把脚本里的api.xiaoyisz全部改成抓包时候看见的apig.xiaoyisz，没能正常跑起来
> > 
> > 
> > 换其他的吧
> 
> 可以给点提示吗？

**Comment by kkkkxl** [comment]
> > > 楼主解决了吗，我把脚本里的api.xiaoyisz全部改成抓包时候看见的apig.xiaoyisz，没能正常跑起来
> > 
> > 
> > 换其他的吧
> 
> 可以给点提示吗？ 感恩

https://t.me/maidmer 你加我tg吧 我发给你
